### ISSUE TITLE
Error on BetaGo when starting

### ISSUE THREAD

**Issue by AMakeApp** [maxpumperla/betago#21]
When I start Go on browser, BetaGo don't run properly.
What should I do?

taewoo@Linux-Workstation:~/Code/betago$ python run_demo.py Using TensorFlow backend.
/home/taewoo/Code/betago/betago/model.py:7: ExtDeprecationWarning: Importing flask.ext.cors is deprecated, use flask_cors instead.
  from flask.ext.cors import CORS
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [17/Jan/2017 22:51:59] "OPTIONS /prediction HTTP/1.1" 200 -
127.0.0.1 - - [17/Jan/2017 22:51:59] "POST /prediction HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/taewoo/.local/lib/python2.7/site-packages/flask/app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/taewoo/.local/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/taewoo/.local/lib/python2.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/taewoo/.local/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/taewoo/.local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/taewoo/.local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/taewoo/.local/lib/python2.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/taewoo/.local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/taewoo/.local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/taewoo/.local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/taewoo/Code/betago/betago/model.py", line 53, in next_move
    bot_row, bot_col = self.bot.select_move('b')
  File "/home/taewoo/Code/betago/betago/model.py", line 109, in select_move
    self._move_generator(bot_color))
  File "/home/taewoo/Code/betago/betago/model.py", line 218, in get_first_valid_move
    for move in move_generator:
  File "/home/taewoo/Code/betago/betago/model.py", line 133, in _model_moves
    pred = np.squeeze(self.model.predict(X))
  File "/home/taewoo/.local/lib/python2.7/site-packages/keras/models.py", line 716, in predict
    return self.model.predict(x, batch_size=batch_size, verbose=verbose)
  File "/home/taewoo/.local/lib/python2.7/site-packages/keras/engine/training.py", line 1216, in predict
    self._make_predict_function()
  File "/home/taewoo/.local/lib/python2.7/site-packages/keras/engine/training.py", line 751, in _make_predict_function
    **kwargs)
  File "/home/taewoo/.local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 1621, in function
    return Function(inputs, outputs, updates=updates)
  File "/home/taewoo/.local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 1579, in __init__
    with tf.control_dependencies(self.outputs):
  File "/home/taewoo/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3487, in control_dependencies
    return get_default_graph().control_dependencies(control_inputs)
  File "/home/taewoo/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3218, in control_dependencies
    c = self.as_graph_element(c)
  File "/home/taewoo/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2318, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/home/taewoo/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2397, in _as_graph_element_locked
    raise ValueError("Tensor %s is not an element of this graph." % obj)
ValueError: Tensor Tensor("Softmax:0", shape=(?, 361), dtype=float32) is not an element of this graph.

**Comment by cdmalon** [comment]
@AMakeApp I worked around this in #24 by switching the backend from TensorFlow to Theano.  Edit your ```~/.keras/keras.json``` file to specify ```theano``` as the value of ```backend``` and try again; see https://keras.io/backend/ for details.

After that, if you're having trouble playing in the terminal, then try playing from a real web browser, by running a second web server (on port 80 or something, in addition to Flask which will be running through Python on port 5000), and copy the ```ui/``` subdirectory over there.  Load ```demoBot.html``` in order to play.  Change ```localhost``` to your external IP address in that file, if you do so.

**Comment by AMakeApp** [comment]
Thank you! Changing keras' backend from tensorflow to theano, it works very well! :D

**Comment by rocketinventor** [comment]
I think that this also helped with some issues I was having in #18.
